import { useState } from 'react';

const BADGE_CLASS = {
  'Strong Buy':  'badge-strong-buy',
  'Buy':         'badge-buy',
  'Hold':        'badge-hold',
  'Sell':        'badge-sell',
  'Strong Sell': 'badge-strong-sell',
};

const BADGE_ICON = {
  'Strong Buy': '▲▲', 'Buy': '▲', 'Hold': '●', 'Sell': '▼', 'Strong Sell': '▼▼',
};

export default function AIRecommendation({ analysis, loading, error, onAnalyze, aiAvailable }) {
  const [hasRequested, setHasRequested] = useState(false);

  const handleClick = () => {
    setHasRequested(true);
    onAnalyze();
  };

  if (!aiAvailable) {
    return (
      <div className="ai-section">
        <div className="kpi-section-header">
          <span className="kpi-section-title">AI Analysis</span>
        </div>
        <div className="info-banner">
          <span style={{ fontSize: 22 }}>🔑</span>
          <div>
            <strong>AI features disabled</strong><br />
            Add your <strong>ANTHROPIC_API_KEY</strong> to the <code>.env</code> file to unlock AI recommendations,
            bull &amp; bear case analysis, and press summaries.
            Costs ~$0.05–0.20 per session. Get a key at{' '}
            <span style={{ color: 'var(--gold)' }}>console.anthropic.com</span>.
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="ai-section">
      <div className="kpi-section-header" style={{ justifyContent: 'space-between' }}>
        <span className="kpi-section-title">AI Analysis</span>
        {!loading && !analysis && (
          <button className="btn btn-gold btn-sm" onClick={handleClick}>
            ✦ Generate Analysis
          </button>
        )}
        {analysis && (
          <button className="btn btn-ghost btn-sm" onClick={handleClick}>
            ↺ Refresh
          </button>
        )}
      </div>

      {!hasRequested && !analysis && (
        <div className="card" style={{ padding: '40px', textAlign: 'center' }}>
          <p style={{ color: 'var(--text-2)', marginBottom: 20 }}>
            Get an AI-powered investment analysis based on all 19 KPIs above.
          </p>
          <button className="btn btn-gold" onClick={handleClick}>
            ✦ Generate Analysis
          </button>
        </div>
      )}

      {loading && (
        <div className="card loading-row">
          <span className="spinner" />
          Analysing {19} KPIs with Claude…
        </div>
      )}

      {error && !loading && (
        <div className="error-banner">
          <span>⚠</span>
          <span>{error}</span>
        </div>
      )}

      {analysis && !loading && (
        <div className="card ai-card">
          <div className="ai-header">
            <span className={`recommendation-badge ${BADGE_CLASS[analysis.recommendation] || 'badge-hold'}`}>
              {BADGE_ICON[analysis.recommendation]} {analysis.recommendation}
            </span>
            <div className="confidence-wrap">
              <span className="confidence-label">Confidence</span>
              <div className="confidence-bar-bg">
                <div className="confidence-bar-fill" style={{ width: `${analysis.confidence}%` }} />
              </div>
              <span className="confidence-score">{analysis.confidence}/100</span>
            </div>
          </div>

          <div className="ai-cases">
            <div className="ai-case bull">
              <div className="ai-case-title">Bull Case</div>
              <ul className="ai-case-list">
                {(analysis.bullCase || []).map((pt, i) => <li key={i}>{pt}</li>)}
              </ul>
            </div>
            <div className="ai-case bear">
              <div className="ai-case-title">Bear Case</div>
              <ul className="ai-case-list">
                {(analysis.bearCase || []).map((pt, i) => <li key={i}>{pt}</li>)}
              </ul>
            </div>
          </div>

          {analysis.summary && (
            <div className="ai-summary">{analysis.summary}</div>
          )}

          <div className="ai-disclaimer">
            ⚠ This analysis is generated by AI for informational purposes only and does not constitute financial advice.
            Always conduct your own research and consult a qualified financial adviser before making investment decisions.
          </div>
        </div>
      )}
    </div>
  );
}
