export const investorLenses = [
  {
    id:      'buffett',
    name:    'Warren Buffett',
    initials:'WB',
    title:   'Berkshire Hathaway',
    tagline: 'Quality moat at a fair price',
    quote:   "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.",
    source:  'Berkshire Hathaway Annual Letters (1977–present) · The Warren Buffett Way (Hagstrom)',
    accent:  '#f59e0b',
    focusKPIs: ['roe','grossMargin','netProfitMargin','operatingMargin','debtToEquity','interestCoverage','fcfYield','peRatio'],
    criteria: [
      { key: 'roe',             label: 'Return on Equity',     min: 0.15,  unit: '%',  threshold: '>15%',    why: 'Proxy for durable competitive advantage' },
      { key: 'grossMargin',     label: 'Gross Margin',         min: 0.40,  unit: '%',  threshold: '>40%',    why: 'Pricing power = moat' },
      { key: 'netProfitMargin', label: 'Net Profit Margin',    min: 0.10,  unit: '%',  threshold: '>10%',    why: 'Real profitability' },
      { key: 'operatingMargin', label: 'Operating Margin',     min: 0.15,  unit: '%',  threshold: '>15%',    why: 'Operational strength' },
      { key: 'debtToEquity',    label: 'Debt / Equity',        max: 0.5,   unit: '×',  threshold: '<0.5×',   why: 'Avoids leverage' },
      { key: 'interestCoverage',label: 'Interest Coverage',    min: 5,     unit: '×',  threshold: '>5×',     why: 'Debt comfortably serviced' },
      { key: 'fcfYield',        label: 'FCF Yield',            min: 0.04,  unit: '%',  threshold: '>4%',     why: '"Owner earnings" — cash the owner actually receives' },
      { key: 'peRatio',         label: 'P/E Ratio',            min: 10, max: 25, unit: '×', threshold: '10–25×', why: 'Fair price, not speculative' },
    ],
  },
  {
    id:      'dalio',
    name:    'Ray Dalio',
    initials:'RD',
    title:   'Bridgewater Associates',
    tagline: 'Resilient balance sheet through all cycles',
    quote:   'He who lives by the crystal ball will eat shattered glass. Build portfolios that can withstand any environment.',
    source:  'Principles (2017) · How the Economic Machine Works · Bridgewater research',
    accent:  '#38bdf8',
    focusKPIs: ['debtToEquity','currentRatio','quickRatio','interestCoverage','netDebt','roa','fcfYield','assetTurnover'],
    criteria: [
      { key: 'debtToEquity',    label: 'Debt / Equity',        max: 0.5,   unit: '×',  threshold: '<0.5×',   why: 'Core to his debt-cycle obsession' },
      { key: 'currentRatio',    label: 'Current Ratio',        min: 2.0,   unit: '×',  threshold: '>2.0×',   why: 'Liquidity to survive downturns' },
      { key: 'quickRatio',      label: 'Quick Ratio',          min: 1.0,   unit: '×',  threshold: '>1.0×',   why: 'No reliance on inventory in a crisis' },
      { key: 'interestCoverage',label: 'Interest Coverage',    min: 5,     unit: '×',  threshold: '>5×',     why: 'Can service debt in a bad environment' },
      { key: 'netDebt',         label: 'Net Debt',             max: 0,     unit: '$',  threshold: '≤0',      why: 'Negative net debt = fortress balance sheet' },
      { key: 'roa',             label: 'Return on Assets',     min: 0.05,  unit: '%',  threshold: '>5%',     why: 'Asset productivity across cycles' },
      { key: 'fcfYield',        label: 'FCF Yield',            min: 0.03,  unit: '%',  threshold: '>3%',     why: 'Real cash generation, not accounting profits' },
      { key: 'assetTurnover',   label: 'Asset Turnover',       min: 0.8,   unit: '×',  threshold: '>0.8×',   why: 'Efficient use of capital base' },
    ],
  },
  {
    id:      'lynch',
    name:    'Peter Lynch',
    initials:'PL',
    title:   'Fidelity Magellan Fund',
    tagline: 'Growth at a reasonable price',
    quote:   'Invest in what you know. Your edge is knowing your industry better than any Wall Street analyst.',
    source:  'One Up on Wall Street (1989) · Beating the Street (1993)',
    accent:  '#22c55e',
    focusKPIs: ['peRatio','netProfitMargin','debtToEquity','inventoryTurnover','assetTurnover','roe','fcfYield','ebitdaMargin'],
    criteria: [
      { key: 'peRatio',          label: 'P/E Ratio',           max: 20,    unit: '×',  threshold: '<20×',    why: "PEG-aware — won't overpay for growth" },
      { key: 'netProfitMargin',  label: 'Net Profit Margin',   min: 0.05,  unit: '%',  threshold: '>5%',     why: 'Company is actually making money' },
      { key: 'debtToEquity',     label: 'Debt / Equity',       max: 0.35,  unit: '×',  threshold: '<0.35×',  why: 'Debt is a red flag in consumer/growth stocks' },
      { key: 'inventoryTurnover',label: 'Inventory Turnover',  min: 4,     unit: '×',  threshold: '>4×',     why: 'Products moving = healthy business' },
      { key: 'assetTurnover',    label: 'Asset Turnover',      min: 0.8,   unit: '×',  threshold: '>0.8×',   why: 'Productive capital deployment' },
      { key: 'roe',              label: 'Return on Equity',    min: 0.15,  unit: '%',  threshold: '>15%',    why: 'Management creating shareholder value' },
      { key: 'fcfYield',         label: 'FCF Yield',           min: 0.03,  unit: '%',  threshold: '>3%',     why: 'Cash is king' },
      { key: 'ebitdaMargin',     label: 'EBITDA Margin',       min: 0.10,  unit: '%',  threshold: '>10%',    why: 'Operational cash generation' },
    ],
  },
  {
    id:      'graham',
    name:    'Benjamin Graham',
    initials:'BG',
    title:   'Columbia Business School',
    tagline: 'Margin of safety — buy cheap, stay safe',
    quote:   'The stock market is a voting machine in the short run and a weighing machine in the long run.',
    source:  'The Intelligent Investor (1949) · Security Analysis (1934, with David Dodd)',
    accent:  '#a855f7',
    focusKPIs: ['peRatio','pbRatio','currentRatio','quickRatio','debtToEquity','netProfitMargin','interestCoverage','roe'],
    criteria: [
      { key: 'peRatio',         label: 'P/E Ratio',           max: 15,    unit: '×',  threshold: '<15×',    why: 'Margin of safety on price — never overpay' },
      { key: 'pbRatio',         label: 'P/B Ratio',           max: 1.5,   unit: '×',  threshold: '<1.5×',   why: 'Buy below or close to book value' },
      { key: 'currentRatio',    label: 'Current Ratio',       min: 2.0,   unit: '×',  threshold: '>2.0×',   why: 'Mandatory liquidity cushion for defensive investors' },
      { key: 'quickRatio',      label: 'Quick Ratio',         min: 1.0,   unit: '×',  threshold: '>1.0×',   why: 'Immediate solvency test' },
      { key: 'debtToEquity',    label: 'Debt / Equity',       max: 0.5,   unit: '×',  threshold: '<0.5×',   why: 'Financial soundness — conservatism in the balance sheet' },
      { key: 'netProfitMargin', label: 'Net Profit Margin',   min: 0.03,  unit: '%',  threshold: '>3%',     why: 'Consistent, positive earnings record required' },
      { key: 'interestCoverage',label: 'Interest Coverage',   min: 3,     unit: '×',  threshold: '>3×',     why: 'Comfortable debt service capacity' },
      { key: 'roe',             label: 'Return on Equity',    min: 0.10,  unit: '%',  threshold: '>10%',    why: 'Adequate, reliable return on capital' },
    ],
  },
  {
    id:      'munger',
    name:    'Charlie Munger',
    initials:'CM',
    title:   'Berkshire Hathaway',
    tagline: 'Wonderful business, held forever',
    quote:   "It's not supposed to be easy. Anyone who finds it easy is stupid.",
    source:  "Poor Charlie's Almanack (2005) · Berkshire Hathaway Annual Letters",
    accent:  '#ec4899',
    focusKPIs: ['roe','grossMargin','operatingMargin','netProfitMargin','roa','debtToEquity','fcfYield','currentRatio'],
    criteria: [
      { key: 'roe',             label: 'Return on Equity',    min: 0.20,  unit: '%',  threshold: '>20%',    why: 'Evidence of exceptional, durable management' },
      { key: 'grossMargin',     label: 'Gross Margin',        min: 0.45,  unit: '%',  threshold: '>45%',    why: "Wide moat — pricing power competitors can't erode" },
      { key: 'operatingMargin', label: 'Operating Margin',    min: 0.20,  unit: '%',  threshold: '>20%',    why: 'Operational excellence at scale' },
      { key: 'netProfitMargin', label: 'Net Profit Margin',   min: 0.15,  unit: '%',  threshold: '>15%',    why: 'True earnings power, not accounting tricks' },
      { key: 'roa',             label: 'Return on Assets',    min: 0.10,  unit: '%',  threshold: '>10%',    why: 'Capital efficiency — doing more with less' },
      { key: 'debtToEquity',    label: 'Debt / Equity',       max: 0.3,   unit: '×',  threshold: '<0.3×',   why: "Great businesses don't need excessive debt" },
      { key: 'fcfYield',        label: 'FCF Yield',           min: 0.05,  unit: '%',  threshold: '>5%',     why: 'The actual owner earnings Munger & Buffett prize' },
      { key: 'currentRatio',    label: 'Current Ratio',       min: 1.5,   unit: '×',  threshold: '>1.5×',   why: 'Comfortable near-term financial position' },
    ],
  },
  {
    id:      'fisher',
    name:    'Philip Fisher',
    initials:'PF',
    title:   'Fisher & Company',
    tagline: 'Great growth companies held for decades',
    quote:   'The stock market is filled with individuals who know the price of everything, but the value of nothing.',
    source:  'Common Stocks and Uncommon Profits (1958) · Paths to Wealth Through Common Stocks (1960)',
    accent:  '#f97316',
    focusKPIs: ['grossMargin','operatingMargin','roe','roa','netProfitMargin','ebitdaMargin','assetTurnover','fcfYield'],
    criteria: [
      { key: 'grossMargin',     label: 'Gross Margin',        min: 0.35,  unit: '%',  threshold: '>35%',    why: 'Strong product differentiation in a growing market' },
      { key: 'operatingMargin', label: 'Operating Margin',    min: 0.15,  unit: '%',  threshold: '>15%',    why: 'Growth story translates to real profits' },
      { key: 'roe',             label: 'Return on Equity',    min: 0.20,  unit: '%',  threshold: '>20%',    why: 'Management compounding capital at exceptional rates' },
      { key: 'roa',             label: 'Return on Assets',    min: 0.08,  unit: '%',  threshold: '>8%',     why: 'Asset-light businesses preferred for long-term compounding' },
      { key: 'netProfitMargin', label: 'Net Profit Margin',   min: 0.10,  unit: '%',  threshold: '>10%',    why: 'Sustained profitability through the growth cycle' },
      { key: 'ebitdaMargin',    label: 'EBITDA Margin',       min: 0.15,  unit: '%',  threshold: '>15%',    why: 'Operational cash generation supports R&D investment' },
      { key: 'assetTurnover',   label: 'Asset Turnover',      min: 0.6,   unit: '×',  threshold: '>0.6×',   why: 'Productive capital deployment in growing markets' },
      { key: 'fcfYield',        label: 'FCF Yield',           min: 0.03,  unit: '%',  threshold: '>3%',     why: 'Free cash flow funds the next wave of growth internally' },
    ],
  },
];
