export const investorLenses = [
  {
    id:      'buffett',
    name:    'Warren Buffett',
    initials:'WB',
    title:   'Berkshire Hathaway',
    tagline: 'Quality moat at a fair price',
    quote:   "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.",
    source:  'Berkshire Hathaway Annual Letters (1977–present) · The Warren Buffett Way (Hagstrom)',
    accent:  '#f59e0b',
    focusKPIs: ['roe','grossMargin','netProfitMargin','operatingMargin','debtToEquity','interestCoverage','fcfYield','peRatio'],
    criteria: [
      { key: 'roe',             label: 'Return on Equity',     min: 15,   unit: '%',  threshold: '>15%',    why: 'Proxy for durable competitive advantage' },
      { key: 'grossMargin',     label: 'Gross Margin',         min: 40,   unit: '%',  threshold: '>40%',    why: 'Pricing power = moat' },
      { key: 'netProfitMargin', label: 'Net Profit Margin',    min: 10,   unit: '%',  threshold: '>10%',    why: 'Real profitability' },
      { key: 'operatingMargin', label: 'Operating Margin',     min: 15,   unit: '%',  threshold: '>15%',    why: 'Operational strength' },
      { key: 'debtToEquity',    label: 'Debt / Equity',        max: 0.5,  unit: '×',  threshold: '<0.5×',   why: 'Avoids leverage' },
      { key: 'interestCoverage',label: 'Interest Coverage',    min: 5,    unit: '×',  threshold: '>5×',     why: 'Debt comfortably serviced' },
      { key: 'fcfYield',        label: 'FCF Yield',            min: 4,    unit: '%',  threshold: '>4%',     why: '"Owner earnings" — cash the owner actually receives' },
      { key: 'peRatio',         label: 'P/E Ratio',            min: 10, max: 25, unit: '×', threshold: '10–25×', why: 'Fair price, not speculative' },
    ],
  },
  {
    id:      'dalio',
    name:    'Ray Dalio',
    initials:'RD',
    title:   'Bridgewater Associates',
    tagline: 'Resilient balance sheet through all cycles',
    quote:   'He who lives by the crystal ball will eat shattered glass. Build portfolios that can withstand any environment.',
    source:  'Principles (2017) · How the Economic Machine Works · Bridgewater research',
    accent:  '#38bdf8',
    focusKPIs: ['debtToEquity','currentRatio','quickRatio','interestCoverage','netDebt','roa','fcfYield','assetTurnover'],
    criteria: [
      { key: 'debtToEquity',    label: 'Debt / Equity',        max: 0.5,  unit: '×',  threshold: '<0.5×',   why: 'Core to his debt-cycle obsession' },
      { key: 'currentRatio',    label: 'Current Ratio',        min: 2.0,  unit: '×',  threshold: '>2.0×',   why: 'Liquidity to survive downturns' },
      { key: 'quickRatio',      label: 'Quick Ratio',          min: 1.0,  unit: '×',  threshold: '>1.0×',   why: 'No reliance on inventory in a crisis' },
      { key: 'interestCoverage',label: 'Interest Coverage',    min: 5,    unit: '×',  threshold: '>5×',     why: 'Can service debt in a bad environment' },
      { key: 'netDebt',         label: 'Net Debt',             max: 0,    unit: '$B', threshold: '≤0',      why: 'Negative net debt = fortress balance sheet' },
      { key: 'roa',             label: 'Return on Assets',     min: 5,    unit: '%',  threshold: '>5%',     why: 'Asset productivity across cycles' },
      { key: 'fcfYield',        label: 'FCF Yield',            min: 3,    unit: '%',  threshold: '>3%',     why: 'Real cash generation, not accounting profits' },
      { key: 'assetTurnover',   label: 'Asset Turnover',       min: 0.8,  unit: '×',  threshold: '>0.8×',   why: 'Efficient use of capital base' },
    ],
  },
  {
    id:      'lynch',
    name:    'Peter Lynch',
    initials:'PL',
    title:   'Fidelity Magellan Fund',
    tagline: 'Growth at a reasonable price',
    quote:   'Invest in what you know. Your edge is knowing your industry better than any Wall Street analyst.',
    source:  'One Up on Wall Street (1989) · Beating the Street (1993)',
    accent:  '#22c55e',
    focusKPIs: ['peRatio','netProfitMargin','debtToEquity','inventoryTurnover','assetTurnover','roe','fcfYield','ebitdaMargin'],
    criteria: [
      { key: 'peRatio',          label: 'P/E Ratio',           max: 20,   unit: '×',  threshold: '<20×',    why: 'PEG-aware — won\'t overpay for growth' },
      { key: 'netProfitMargin',  label: 'Net Profit Margin',   min: 5,    unit: '%',  threshold: '>5%',     why: 'Company is actually making money' },
      { key: 'debtToEquity',     label: 'Debt / Equity',       max: 0.35, unit: '×',  threshold: '<0.35×',  why: 'Debt is a red flag in consumer/growth stocks' },
      { key: 'inventoryTurnover',label: 'Inventory Turnover',  min: 4,    unit: '×',  threshold: '>4×',     why: 'Products moving = healthy business' },
      { key: 'assetTurnover',    label: 'Asset Turnover',      min: 0.8,  unit: '×',  threshold: '>0.8×',   why: 'Productive capital deployment' },
      { key: 'roe',              label: 'Return on Equity',    min: 15,   unit: '%',  threshold: '>15%',    why: 'Management creating shareholder value' },
      { key: 'fcfYield',         label: 'FCF Yield',           min: 3,    unit: '%',  threshold: '>3%',     why: 'Cash is king' },
      { key: 'ebitdaMargin',     label: 'EBITDA Margin',       min: 10,   unit: '%',  threshold: '>10%',    why: 'Operational cash generation' },
    ],
  },
];
